// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/task.proto

package task

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_proto_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_task_proto_rawDescGZIP(), []int{0}
}

type GetTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	IdExpression  int64                  `protobuf:"varint,2,opt,name=id_expression,json=idExpression,proto3" json:"id_expression,omitempty"`
	IdTask        int64                  `protobuf:"varint,3,opt,name=id_task,json=idTask,proto3" json:"id_task,omitempty"`
	Arg1          float32                `protobuf:"fixed32,4,opt,name=arg1,proto3" json:"arg1,omitempty"`
	Arg2          float32                `protobuf:"fixed32,5,opt,name=arg2,proto3" json:"arg2,omitempty"`
	Operation     string                 `protobuf:"bytes,6,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResponse) Reset() {
	*x = GetTaskResponse{}
	mi := &file_proto_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResponse) ProtoMessage() {}

func (x *GetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_task_proto_rawDescGZIP(), []int{1}
}

func (x *GetTaskResponse) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *GetTaskResponse) GetIdExpression() int64 {
	if x != nil {
		return x.IdExpression
	}
	return 0
}

func (x *GetTaskResponse) GetIdTask() int64 {
	if x != nil {
		return x.IdTask
	}
	return 0
}

func (x *GetTaskResponse) GetArg1() float32 {
	if x != nil {
		return x.Arg1
	}
	return 0
}

func (x *GetTaskResponse) GetArg2() float32 {
	if x != nil {
		return x.Arg2
	}
	return 0
}

func (x *GetTaskResponse) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

type PostTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	IdExpression  int64                  `protobuf:"varint,2,opt,name=id_expression,json=idExpression,proto3" json:"id_expression,omitempty"`
	IdTask        int64                  `protobuf:"varint,3,opt,name=id_task,json=idTask,proto3" json:"id_task,omitempty"`
	OperationTime int64                  `protobuf:"varint,4,opt,name=operation_time,json=operationTime,proto3" json:"operation_time,omitempty"`
	Result        float32                `protobuf:"fixed32,5,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostTaskRequest) Reset() {
	*x = PostTaskRequest{}
	mi := &file_proto_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostTaskRequest) ProtoMessage() {}

func (x *PostTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostTaskRequest.ProtoReflect.Descriptor instead.
func (*PostTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_task_proto_rawDescGZIP(), []int{2}
}

func (x *PostTaskRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *PostTaskRequest) GetIdExpression() int64 {
	if x != nil {
		return x.IdExpression
	}
	return 0
}

func (x *PostTaskRequest) GetIdTask() int64 {
	if x != nil {
		return x.IdTask
	}
	return 0
}

func (x *PostTaskRequest) GetOperationTime() int64 {
	if x != nil {
		return x.OperationTime
	}
	return 0
}

func (x *PostTaskRequest) GetResult() float32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type PostTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostTaskResponse) Reset() {
	*x = PostTaskResponse{}
	mi := &file_proto_task_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostTaskResponse) ProtoMessage() {}

func (x *PostTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostTaskResponse.ProtoReflect.Descriptor instead.
func (*PostTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_task_proto_rawDescGZIP(), []int{3}
}

var File_proto_task_proto protoreflect.FileDescriptor

const file_proto_task_proto_rawDesc = "" +
	"\n" +
	"\x10proto/task.proto\x12\x04task\"\x10\n" +
	"\x0eGetTaskRequest\"\xab\x01\n" +
	"\x0fGetTaskResponse\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12#\n" +
	"\rid_expression\x18\x02 \x01(\x03R\fidExpression\x12\x17\n" +
	"\aid_task\x18\x03 \x01(\x03R\x06idTask\x12\x12\n" +
	"\x04arg1\x18\x04 \x01(\x02R\x04arg1\x12\x12\n" +
	"\x04arg2\x18\x05 \x01(\x02R\x04arg2\x12\x1c\n" +
	"\toperation\x18\x06 \x01(\tR\toperation\"\xa4\x01\n" +
	"\x0fPostTaskRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12#\n" +
	"\rid_expression\x18\x02 \x01(\x03R\fidExpression\x12\x17\n" +
	"\aid_task\x18\x03 \x01(\x03R\x06idTask\x12%\n" +
	"\x0eoperation_time\x18\x04 \x01(\x03R\roperationTime\x12\x16\n" +
	"\x06result\x18\x05 \x01(\x02R\x06result\"\x12\n" +
	"\x10PostTaskResponse2\x80\x01\n" +
	"\vTaskService\x126\n" +
	"\aGetTask\x12\x14.task.GetTaskRequest\x1a\x15.task.GetTaskResponse\x129\n" +
	"\bPostTask\x12\x15.task.PostTaskRequest\x1a\x16.task.PostTaskResponseB5Z3github.com/kingofhandsomes/calculator-go/proto;taskb\x06proto3"

var (
	file_proto_task_proto_rawDescOnce sync.Once
	file_proto_task_proto_rawDescData []byte
)

func file_proto_task_proto_rawDescGZIP() []byte {
	file_proto_task_proto_rawDescOnce.Do(func() {
		file_proto_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_task_proto_rawDesc), len(file_proto_task_proto_rawDesc)))
	})
	return file_proto_task_proto_rawDescData
}

var file_proto_task_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_task_proto_goTypes = []any{
	(*GetTaskRequest)(nil),   // 0: task.GetTaskRequest
	(*GetTaskResponse)(nil),  // 1: task.GetTaskResponse
	(*PostTaskRequest)(nil),  // 2: task.PostTaskRequest
	(*PostTaskResponse)(nil), // 3: task.PostTaskResponse
}
var file_proto_task_proto_depIdxs = []int32{
	0, // 0: task.TaskService.GetTask:input_type -> task.GetTaskRequest
	2, // 1: task.TaskService.PostTask:input_type -> task.PostTaskRequest
	1, // 2: task.TaskService.GetTask:output_type -> task.GetTaskResponse
	3, // 3: task.TaskService.PostTask:output_type -> task.PostTaskResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_task_proto_init() }
func file_proto_task_proto_init() {
	if File_proto_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_task_proto_rawDesc), len(file_proto_task_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_task_proto_goTypes,
		DependencyIndexes: file_proto_task_proto_depIdxs,
		MessageInfos:      file_proto_task_proto_msgTypes,
	}.Build()
	File_proto_task_proto = out.File
	file_proto_task_proto_goTypes = nil
	file_proto_task_proto_depIdxs = nil
}
